name: 清理工作流

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜运行
  workflow_dispatch:

jobs:
  delete_workflow_runs:
    runs-on: ubuntu-latest
    
    steps:
    - name: 删除所有工作流运行记录
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
